### ISSUE TITLE
DeserializationError cannot deserialize: unknown error handler name 'rosmsg'

### ISSUE THREAD

**Issue by jaymwong** [tork-a/melfa_robot#29]
We are trying to use this ROS driver for our MELFA RV7FRL robot and have been getting a de-serialization error when running the `melfa_driver.launch`. We've tried this both on the real robot as well as `loopback:=true` and this de-serialization error comes up, 

```
ROS_MASTER_URI=http://localhost:11311

process[melfa_driver-1]: started with pid [8224]
process[melfa_loopback-2]: started with pid [8225]
process[controller_spawner-3]: started with pid [8226]
process[robot_state_publisher-4]: started with pid [8246]
[melfa_loopback-2] process has died [pid 8225, exit code -4, cmd /home/saw/wizard/devel/lib/melfa_driver/melfa_loopback_node __name:=melfa_loopback __log:=/home/saw/.ros/log/5bd60418-e887-11ea-9022-1c1b0d05d0ee/melfa_loopback-2.log].
log file: /home/saw/.ros/log/5bd60418-e887-11ea-9022-1c1b0d05d0ee/melfa_loopback-2*.log
[INFO] [1598549074.990473]: Controller Spawner: Waiting for service controller_manager/load_controller
[INFO] [1598549074.992836]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1598549074.995068]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1598549074.996878]: Loading controller: joint_state_controller
Traceback (most recent call last):
  File "/home/saw/wizard/src/externals/ros_control/controller_manager/scripts/spawner", line 208, in <module>
    if __name__ == '__main__': main()
  File "/home/saw/wizard/src/externals/ros_control/controller_manager/scripts/spawner", line 186, in main
    resp = load_controller(name)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 525, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: receive_once[/controller_manager/load_controller]: DeserializationError cannot deserialize: unknown error handler name 'rosmsg'
[INFO] [1598549075.094638]: Shutting down spawner. Stopping and unloading controllers...
[INFO] [1598549075.095132]: Stopping all controllers...
[WARN] [1598549075.106303]: Controller Spawner error while taking down controllers: transport error completing service call: receive_once[/controller_manager/switch_controller]: DeserializationError cannot deserialize: unknown error handler name 'rosmsg'
[controller_spawner-3] process has died [pid 8226, exit code 1, cmd /home/saw/wizard/src/externals/ros_control/controller_manager/scripts/spawner joint_state_controller joint_trajectory_controller __name:=controller_spawner __log:=/home/saw/.ros/log/5bd60418-e887-11ea-9022-1c1b0d05d0ee/controller_spawner-3.log].
```

On the robot end, we followed the README and ran the _real time external control program_ as well as set the IP accordingly, both on the robot as well as the ROS PC. 

It's very interesting to us that even in loopback mode, we are getting this error. We've even tried building `ros_control/kinetic-devel` from source to see if this problem gets resolved without any luck. 

Any ideas regarding this? 

Also, could you kindly attach the SHA of the latest commit from `ros_control` that is compatible with this driver? Perhaps we can start from there. Any other version numbers of the dependencies would be greatly appreciated.

**Comment by gavanderhoorn** [comment]
This is most likely not a problem with the driver here or with `ros_control`, but is caused by a regression in `genpy`.

See ros/genpy#132.

Making sure you have all packages up-to-date should mitigate this though.

**Comment by jaymwong** [comment]
@gavanderhoorn Doing a `sudo apt-get upgrade` seems to resolve this issue.
Thank you! Closing now.
